//
// Created by douglas on 6/28/17.
//

#ifndef INTERACTIVEOBJECT_OP_H
#define INTERACTIVEOBJECT_OP_H


enum class Op{
    OPTION_MENU, OPTION_SELECTION, OPTION_ROT, OPTION_TRAN, OPTION_SCA
};


#endif //INTERACTIVEOBJECT_OP_H
